In [32]:
!pip install optuna

The folder you are executing pip from can no longer be found.

In [33]:
import pandas as pd
import pickle
import numpy as np 

import optuna 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score

from sklearn.metrics import accuracy_score, f1_score, classification_report

In [34]:
link = '/Users/maxkucher/bcs_ai/intent_model/intent_data.csv'
data = pd.read_csv(link)
data

,sequence_id,t,X,Y,vx,vy,speed,motion_class,distance,threat,intent
0,0,0,4.177220,171.095738,0.511380,15.669348,15.677690,2,171.146723,0.180601,retreat
1,0,1,3.879314,188.387388,-0.297907,17.291650,17.294216,2,188.427326,0.151939,retreat
2,0,2,4.546663,205.865374,0.667349,17.477986,17.490722,2,205.915576,0.127562,retreat
3,0,3,4.328316,225.673215,-0.218347,19.807841,19.809044,2,225.714719,0.104649,retreat
4,0,4,4.242576,247.609613,-0.085740,21.936399,21.936566,2,247.645957,0.084040,retreat
...,...,...,...,...,...,...,...,...,...,...,...
49995,4999,5,-81.068057,314.085940,-5.872654,28.590556,29.187462,2,324.379419,0.039016,retreat
49996,4999,6,-84.043635,346.426534,-2.975578,32.340594,32.477194,2,356.475351,0.028304,retreat
49997,4999,7,-87.787146,381.741518,-3.743511,35.314984,35.512842,2,391.705462,0.019900,retreat
49998,4999,8,-92.715497,420.066454,-4.928351,38.324937,38.640515,2,430.176696,0.013545,retreat
49999,4999,9,-95.299433,462.347050,-2.583936,42.280596,42.359479,2,472.066496,0.008909,retreat

In [9]:
# columns_to_drop = ['sequence_id']
# data = data.drop(columns_to_drop, axis='columns')
# data

In [35]:
data['intent'].value_counts()

intent
attack        12720
idle          12700
reposition    12320
retreat       12260
Name: count, dtype: int64

In [36]:
INTENT_MAP = {
    "attack": 0,
    "retreat": 1,
    "reposition": 2,
    "idle": 3
}

data["intent_encoded"] = data["intent"].map(INTENT_MAP)

In [37]:
data = data.drop('intent', axis='columns')
data

,sequence_id,t,X,Y,vx,vy,speed,motion_class,distance,threat,intent_encoded
0,0,0,4.177220,171.095738,0.511380,15.669348,15.677690,2,171.146723,0.180601,1
1,0,1,3.879314,188.387388,-0.297907,17.291650,17.294216,2,188.427326,0.151939,1
2,0,2,4.546663,205.865374,0.667349,17.477986,17.490722,2,205.915576,0.127562,1
3,0,3,4.328316,225.673215,-0.218347,19.807841,19.809044,2,225.714719,0.104649,1
4,0,4,4.242576,247.609613,-0.085740,21.936399,21.936566,2,247.645957,0.084040,1
...,...,...,...,...,...,...,...,...,...,...,...
49995,4999,5,-81.068057,314.085940,-5.872654,28.590556,29.187462,2,324.379419,0.039016,1
49996,4999,6,-84.043635,346.426534,-2.975578,32.340594,32.477194,2,356.475351,0.028304,1
49997,4999,7,-87.787146,381.741518,-3.743511,35.314984,35.512842,2,391.705462,0.019900,1
49998,4999,8,-92.715497,420.066454,-4.928351,38.324937,38.640515,2,430.176696,0.013545,1
49999,4999,9,-95.299433,462.347050,-2.583936,42.280596,42.359479,2,472.066496,0.008909,1

In [38]:
def prepare_sequences(df, seq_len=10):
    X = []
    y = []

    for _, group in df.groupby("sequence_id"):
        group = group.sort_values("t")

        features = group[[
            "X", "Y", "vx", "vy",
            "speed", "motion_class",
            "distance", "threat"
        ]].values

        if len(features) == seq_len:
            X.append(features.flatten())  
            y.append(group["intent_encoded"].iloc[0])

    return np.array(X), np.array(y)

In [39]:
x, y = prepare_sequences(data)

In [40]:
x.shape

(5000, 80)

In [ ]:
# x = data.drop('intent_encoded', axis='columns')
# y = data['intent_encoded']

In [41]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [42]:
def objective(trial):
    model = RandomForestClassifier(
        n_estimators=trial.suggest_int("n_estimators", 50, 300),
        max_depth=trial.suggest_int("max_depth", 2, 32),
        min_samples_split=trial.suggest_int("min_samples_split", 2, 20),
        min_samples_leaf=trial.suggest_int("min_samples_leaf", 1, 20),
        max_features=trial.suggest_categorical("max_features", ["sqrt", "log2", None]),
        n_jobs=-1,
        random_state=42
    )

    score = cross_val_score(model, x_train, y_train)

    return score.mean()

In [43]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

[I 2026-05-09 12:47:16,181] A new study created in memory with name: no-name-91ab2fee-8c6c-4679-a5fe-8ef53bb3d238
[I 2026-05-09 12:47:23,272] Trial 0 finished with value: 1.0 and parameters: {'n_estimators': 242, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 9, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:26,668] Trial 1 finished with value: 1.0 and parameters: {'n_estimators': 129, 'max_depth': 30, 'min_samples_split': 2, 'min_samples_leaf': 14, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:27,399] Trial 2 finished with value: 1.0 and parameters: {'n_estimators': 111, 'max_depth': 7, 'min_samples_split': 11, 'min_samples_leaf': 20, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:29,085] Trial 3 finished with value: 1.0 and parameters: {'n_estimators': 282, 'max_depth': 30, 'min_samples_split': 10, 'min_samples_leaf': 14, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:29,682] Trial 4 finished with value: 1.0 and parameters: {'n_estimators': 94, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 14, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:30,442] Trial 5 finished with value: 1.0 and parameters: {'n_estimators': 112, 'max_depth': 15, 'min_samples_split': 17, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:34,944] Trial 6 finished with value: 1.0 and parameters: {'n_estimators': 179, 'max_depth': 24, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:35,564] Trial 7 finished with value: 1.0 and parameters: {'n_estimators': 99, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 14, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:36,002] Trial 8 finished with value: 1.0 and parameters: {'n_estimators': 66, 'max_depth': 8, 'min_samples_split': 19, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:42,002] Trial 9 finished with value: 1.0 and parameters: {'n_estimators': 219, 'max_depth': 20, 'min_samples_split': 20, 'min_samples_leaf': 18, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:43,858] Trial 10 finished with value: 1.0 and parameters: {'n_estimators': 297, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:49,652] Trial 11 finished with value: 1.0 and parameters: {'n_estimators': 227, 'max_depth': 32, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:53,819] Trial 12 finished with value: 1.0 and parameters: {'n_estimators': 163, 'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:47:57,981] Trial 13 finished with value: 1.0 and parameters: {'n_estimators': 160, 'max_depth': 25, 'min_samples_split': 4, 'min_samples_leaf': 12, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:02,974] Trial 14 finished with value: 1.0 and parameters: {'n_estimators': 250, 'max_depth': 2, 'min_samples_split': 8, 'min_samples_leaf': 16, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:07,876] Trial 15 finished with value: 1.0 and parameters: {'n_estimators': 196, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 12, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:11,449] Trial 16 finished with value: 1.0 and parameters: {'n_estimators': 141, 'max_depth': 28, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:13,052] Trial 17 finished with value: 1.0 and parameters: {'n_estimators': 257, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 17, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:14,510] Trial 18 finished with value: 1.0 and parameters: {'n_estimators': 54, 'max_depth': 27, 'min_samples_split': 13, 'min_samples_leaf': 11, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:17,937] Trial 19 finished with value: 1.0 and parameters: {'n_estimators': 133, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:19,227] Trial 20 finished with value: 1.0 and parameters: {'n_estimators': 203, 'max_depth': 16, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:20,057] Trial 21 finished with value: 1.0 and parameters: {'n_estimators': 123, 'max_depth': 4, 'min_samples_split': 14, 'min_samples_leaf': 20, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:20,582] Trial 22 finished with value: 1.0 and parameters: {'n_estimators': 80, 'max_depth': 7, 'min_samples_split': 11, 'min_samples_leaf': 20, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:21,497] Trial 23 finished with value: 1.0 and parameters: {'n_estimators': 144, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 16, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:24,350] Trial 24 finished with value: 1.0 and parameters: {'n_estimators': 112, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 18, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:25,437] Trial 25 finished with value: 1.0 and parameters: {'n_estimators': 180, 'max_depth': 10, 'min_samples_split': 16, 'min_samples_leaf': 13, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:27,742] Trial 26 finished with value: 1.0 and parameters: {'n_estimators': 91, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:28,809] Trial 27 finished with value: 1.0 and parameters: {'n_estimators': 155, 'max_depth': 21, 'min_samples_split': 9, 'min_samples_leaf': 19, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:34,904] Trial 28 finished with value: 1.0 and parameters: {'n_estimators': 235, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 15, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:36,531] Trial 29 finished with value: 1.0 and parameters: {'n_estimators': 274, 'max_depth': 32, 'min_samples_split': 10, 'min_samples_leaf': 12, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:37,691] Trial 30 finished with value: 1.0 and parameters: {'n_estimators': 198, 'max_depth': 2, 'min_samples_split': 18, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:39,471] Trial 31 finished with value: 1.0 and parameters: {'n_estimators': 295, 'max_depth': 29, 'min_samples_split': 11, 'min_samples_leaf': 14, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:41,137] Trial 32 finished with value: 1.0 and parameters: {'n_estimators': 278, 'max_depth': 29, 'min_samples_split': 13, 'min_samples_leaf': 16, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:42,738] Trial 33 finished with value: 1.0 and parameters: {'n_estimators': 272, 'max_depth': 30, 'min_samples_split': 3, 'min_samples_leaf': 11, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:44,244] Trial 34 finished with value: 1.0 and parameters: {'n_estimators': 252, 'max_depth': 26, 'min_samples_split': 8, 'min_samples_leaf': 14, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:44,973] Trial 35 finished with value: 1.0 and parameters: {'n_estimators': 111, 'max_depth': 22, 'min_samples_split': 12, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:47,136] Trial 36 finished with value: 1.0 and parameters: {'n_estimators': 83, 'max_depth': 17, 'min_samples_split': 2, 'min_samples_leaf': 13, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:47,974] Trial 37 finished with value: 1.0 and parameters: {'n_estimators': 122, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 18, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:48,604] Trial 38 finished with value: 1.0 and parameters: {'n_estimators': 99, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 15, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:55,678] Trial 39 finished with value: 1.0 and parameters: {'n_estimators': 284, 'max_depth': 23, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:56,937] Trial 40 finished with value: 1.0 and parameters: {'n_estimators': 221, 'max_depth': 31, 'min_samples_split': 17, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:57,415] Trial 41 finished with value: 1.0 and parameters: {'n_estimators': 70, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 13, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:58,054] Trial 42 finished with value: 1.0 and parameters: {'n_estimators': 101, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 17, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:48:59,104] Trial 43 finished with value: 1.0 and parameters: {'n_estimators': 173, 'max_depth': 25, 'min_samples_split': 2, 'min_samples_leaf': 14, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:49:05,129] Trial 44 finished with value: 1.0 and parameters: {'n_estimators': 239, 'max_depth': 18, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:49:06,653] Trial 45 finished with value: 1.0 and parameters: {'n_estimators': 56, 'max_depth': 27, 'min_samples_split': 4, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:49:07,522] Trial 46 finished with value: 1.0 and parameters: {'n_estimators': 127, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 15, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:49:11,201] Trial 47 finished with value: 1.0 and parameters: {'n_estimators': 148, 'max_depth': 12, 'min_samples_split': 12, 'min_samples_leaf': 11, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:49:12,462] Trial 48 finished with value: 1.0 and parameters: {'n_estimators': 210, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-05-09 12:49:18,907] Trial 49 finished with value: 1.0 and parameters: {'n_estimators': 263, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 17, 'max_features': None}. Best is trial 0 with value: 1.0.

In [44]:
best_model = RandomForestClassifier(**study.best_params)
best_model.fit(x_train, y_train)

RandomForestClassifier(max_depth=17, max_features=None, min_samples_leaf=9,
                       min_samples_split=4, n_estimators=242)

In [45]:
preds = best_model.predict(x_test)
accuracy = accuracy_score(y_test, preds)
f1 = f1_score(y_test, preds, average="weighted")

print(f"Accuracy: {accuracy} | F1-score: {f1}")

Accuracy: 1.0 | F1-score: 1.0

In [ ]:
# with open("/Users/maxkucher/bcs_ai/intent_model/intent_model.pkl", "wb") as f:
#     pickle.dump(best_model, f)