In [1]:
!pip install optuna

Collecting optuna
  Using cached optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /opt/anaconda3/envs/mlflow3/lib/python3.10/site-packages (from optuna) (1.16.4)
Collecting colorlog (from optuna)
  Using cached colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /opt/anaconda3/envs/mlflow3/lib/python3.10/site-packages (from optuna) (2.0.1)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/mlflow3/lib/python3.10/site-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /opt/anaconda3/envs/mlflow3/lib/python3.10/site-packages (from optuna) (2.0.43)
Requirement already satisfied: tqdm in /opt/anaconda3/envs/mlflow3/lib/python3.10/site-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /opt/anaconda3/envs/mlflow3/lib/python3.10/site-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /opt/anaconda3/envs/mlflow3/lib/python3.10/site-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /opt/anaconda3/envs/mlflow3/lib/python3.10/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: tomli in /opt/anaconda3/envs/mlflow3/lib/python3.10/site-packages (from alembic>=1.5.0->optuna) (2.2.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /opt/anaconda3/envs/mlflow3/lib/python3.10/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.2)
Using cached optuna-4.8.0-py3-none-any.whl (419 kB)
Using cached colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [optuna]2m1/2 [optuna]
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [1]:
import pandas as pd
import pickle
import numpy as np 

import optuna 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score

from sklearn.metrics import accuracy_score, f1_score, classification_report

/opt/anaconda3/envs/mlflow3/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [11]:
link = '/Users/maxkucher/bcs_ai/intent_model/intent_data.csv'
data = pd.read_csv(link)
data

,sequence_id,t,X,Y,vx,vy,speed,motion_class,distance,threat,intent
0,0,0,-60.946138,196.966037,-4.469285,-0.450112,4.491894,-1,206.179658,0.127225,reposition
1,0,1,-55.693151,197.403167,5.252986,0.437131,5.271143,1,205.109087,0.128595,reposition
2,0,2,-60.620444,196.570349,-4.927292,-0.832818,4.997179,-1,205.705470,0.127830,reposition
3,0,3,-65.290447,196.784927,-4.670004,0.214578,4.674931,-1,207.333428,0.125766,reposition
4,0,4,-70.507729,197.183724,-5.217282,0.398797,5.232501,-1,209.410509,0.123180,reposition
...,...,...,...,...,...,...,...,...,...,...,...
49995,4999,5,35.331296,115.564848,0.611553,0.556272,0.826702,1,120.845085,0.298660,idle
49996,4999,6,35.642107,115.796848,0.310811,0.232000,0.387849,1,121.158037,0.297726,idle
49997,4999,7,36.173334,115.432187,0.531227,-0.364662,0.644344,1,120.967350,0.298295,idle
49998,4999,8,36.379956,115.689068,0.206622,0.256881,0.329667,2,121.274324,0.297380,idle
49999,4999,9,36.237136,116.213556,-0.142821,0.524488,0.543586,2,121.732167,0.296022,idle

In [9]:
# columns_to_drop = ['sequence_id']
# data = data.drop(columns_to_drop, axis='columns')
# data

In [12]:
data['intent'].value_counts()

intent
idle          12990
retreat       12650
attack        12390
reposition    11970
Name: count, dtype: int64

In [13]:
INTENT_MAP = {
    "attack": 0,
    "retreat": 1,
    "reposition": 2,
    "idle": 3
}

data["intent_encoded"] = data["intent"].map(INTENT_MAP)

In [14]:
data = data.drop('intent', axis='columns')
data

,sequence_id,t,X,Y,vx,vy,speed,motion_class,distance,threat,intent_encoded
0,0,0,-60.946138,196.966037,-4.469285,-0.450112,4.491894,-1,206.179658,0.127225,2
1,0,1,-55.693151,197.403167,5.252986,0.437131,5.271143,1,205.109087,0.128595,2
2,0,2,-60.620444,196.570349,-4.927292,-0.832818,4.997179,-1,205.705470,0.127830,2
3,0,3,-65.290447,196.784927,-4.670004,0.214578,4.674931,-1,207.333428,0.125766,2
4,0,4,-70.507729,197.183724,-5.217282,0.398797,5.232501,-1,209.410509,0.123180,2
...,...,...,...,...,...,...,...,...,...,...,...
49995,4999,5,35.331296,115.564848,0.611553,0.556272,0.826702,1,120.845085,0.298660,3
49996,4999,6,35.642107,115.796848,0.310811,0.232000,0.387849,1,121.158037,0.297726,3
49997,4999,7,36.173334,115.432187,0.531227,-0.364662,0.644344,1,120.967350,0.298295,3
49998,4999,8,36.379956,115.689068,0.206622,0.256881,0.329667,2,121.274324,0.297380,3
49999,4999,9,36.237136,116.213556,-0.142821,0.524488,0.543586,2,121.732167,0.296022,3

In [15]:
def prepare_sequences(df, seq_len=10):
    X = []
    y = []

    for _, group in df.groupby("sequence_id"):
        group = group.sort_values("t")

        features = group[[
            "X", "Y", "vx", "vy",
            "speed", "motion_class",
            "distance", "threat"
        ]].values

        if len(features) == seq_len:
            X.append(features.flatten())  
            y.append(group["intent_encoded"].iloc[0])

    return np.array(X), np.array(y)

In [16]:
x, y = prepare_sequences(data)

In [21]:
x.shape

(5000, 80)

In [ ]:
# x = data.drop('intent_encoded', axis='columns')
# y = data['intent_encoded']

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [23]:
def objective(trial):
    model = RandomForestClassifier(
        n_estimators=trial.suggest_int("n_estimators", 50, 300),
        max_depth=trial.suggest_int("max_depth", 2, 32),
        min_samples_split=trial.suggest_int("min_samples_split", 2, 20),
        min_samples_leaf=trial.suggest_int("min_samples_leaf", 1, 20),
        max_features=trial.suggest_categorical("max_features", ["sqrt", "log2", None]),
        n_jobs=-1,
        random_state=42
    )

    score = cross_val_score(model, x_train, y_train)

    return score.mean()

In [24]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

[I 2026-04-05 13:37:55,928] A new study created in memory with name: no-name-4a8c2741-670f-4862-a9c1-b33df251534e
[I 2026-04-05 13:37:57,715] Trial 0 finished with value: 1.0 and parameters: {'n_estimators': 81, 'max_depth': 2, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:37:59,357] Trial 1 finished with value: 1.0 and parameters: {'n_estimators': 258, 'max_depth': 23, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:00,400] Trial 2 finished with value: 1.0 and parameters: {'n_estimators': 146, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 15, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:02,231] Trial 3 finished with value: 1.0 and parameters: {'n_estimators': 269, 'max_depth': 27, 'min_samples_split': 10, 'min_samples_leaf': 16, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:06,061] Trial 4 finished with value: 1.0 and parameters: {'n_estimators': 127, 'max_depth': 30, 'min_samples_split': 14, 'min_samples_leaf': 12, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:07,860] Trial 5 finished with value: 1.0 and parameters: {'n_estimators': 58, 'max_depth': 15, 'min_samples_split': 15, 'min_samples_leaf': 16, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:09,733] Trial 6 finished with value: 1.0 and parameters: {'n_estimators': 297, 'max_depth': 23, 'min_samples_split': 9, 'min_samples_leaf': 6, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:11,174] Trial 7 finished with value: 1.0 and parameters: {'n_estimators': 234, 'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 15, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:11,911] Trial 8 finished with value: 1.0 and parameters: {'n_estimators': 108, 'max_depth': 24, 'min_samples_split': 9, 'min_samples_leaf': 15, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:13,238] Trial 9 finished with value: 1.0 and parameters: {'n_estimators': 178, 'max_depth': 25, 'min_samples_split': 9, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:14,850] Trial 10 finished with value: 1.0 and parameters: {'n_estimators': 55, 'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:16,171] Trial 11 finished with value: 1.0 and parameters: {'n_estimators': 209, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:21,933] Trial 12 finished with value: 1.0 and parameters: {'n_estimators': 233, 'max_depth': 11, 'min_samples_split': 19, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:22,503] Trial 13 finished with value: 1.0 and parameters: {'n_estimators': 85, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:27,115] Trial 14 finished with value: 1.0 and parameters: {'n_estimators': 170, 'max_depth': 18, 'min_samples_split': 17, 'min_samples_leaf': 9, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:28,930] Trial 15 finished with value: 1.0 and parameters: {'n_estimators': 298, 'max_depth': 32, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:35,073] Trial 16 finished with value: 1.0 and parameters: {'n_estimators': 203, 'max_depth': 13, 'min_samples_split': 17, 'min_samples_leaf': 19, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:35,723] Trial 17 finished with value: 1.0 and parameters: {'n_estimators': 90, 'max_depth': 7, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:43,339] Trial 18 finished with value: 1.0 and parameters: {'n_estimators': 254, 'max_depth': 21, 'min_samples_split': 6, 'min_samples_leaf': 12, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:44,506] Trial 19 finished with value: 1.0 and parameters: {'n_estimators': 152, 'max_depth': 16, 'min_samples_split': 16, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:49,824] Trial 20 finished with value: 1.0 and parameters: {'n_estimators': 198, 'max_depth': 7, 'min_samples_split': 12, 'min_samples_leaf': 12, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:50,687] Trial 21 finished with value: 1.0 and parameters: {'n_estimators': 137, 'max_depth': 16, 'min_samples_split': 13, 'min_samples_leaf': 20, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:51,396] Trial 22 finished with value: 1.0 and parameters: {'n_estimators': 111, 'max_depth': 19, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:52,381] Trial 23 finished with value: 1.0 and parameters: {'n_estimators': 158, 'max_depth': 20, 'min_samples_split': 18, 'min_samples_leaf': 13, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:52,932] Trial 24 finished with value: 1.0 and parameters: {'n_estimators': 83, 'max_depth': 21, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:53,747] Trial 25 finished with value: 1.0 and parameters: {'n_estimators': 127, 'max_depth': 29, 'min_samples_split': 14, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:54,867] Trial 26 finished with value: 1.0 and parameters: {'n_estimators': 185, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:56,372] Trial 27 finished with value: 1.0 and parameters: {'n_estimators': 225, 'max_depth': 22, 'min_samples_split': 15, 'min_samples_leaf': 18, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:38:58,184] Trial 28 finished with value: 1.0 and parameters: {'n_estimators': 272, 'max_depth': 18, 'min_samples_split': 11, 'min_samples_leaf': 14, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:05,138] Trial 29 finished with value: 1.0 and parameters: {'n_estimators': 261, 'max_depth': 29, 'min_samples_split': 7, 'min_samples_leaf': 17, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:05,658] Trial 30 finished with value: 1.0 and parameters: {'n_estimators': 70, 'max_depth': 27, 'min_samples_split': 14, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:07,348] Trial 31 finished with value: 1.0 and parameters: {'n_estimators': 272, 'max_depth': 28, 'min_samples_split': 10, 'min_samples_leaf': 11, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:08,952] Trial 32 finished with value: 1.0 and parameters: {'n_estimators': 246, 'max_depth': 23, 'min_samples_split': 13, 'min_samples_leaf': 17, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:10,640] Trial 33 finished with value: 1.0 and parameters: {'n_estimators': 275, 'max_depth': 31, 'min_samples_split': 10, 'min_samples_leaf': 14, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:17,683] Trial 34 finished with value: 1.0 and parameters: {'n_estimators': 283, 'max_depth': 26, 'min_samples_split': 15, 'min_samples_leaf': 16, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:18,689] Trial 35 finished with value: 1.0 and parameters: {'n_estimators': 113, 'max_depth': 24, 'min_samples_split': 8, 'min_samples_leaf': 13, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:20,189] Trial 36 finished with value: 1.0 and parameters: {'n_estimators': 220, 'max_depth': 13, 'min_samples_split': 12, 'min_samples_leaf': 16, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:23,960] Trial 37 finished with value: 1.0 and parameters: {'n_estimators': 152, 'max_depth': 25, 'min_samples_split': 16, 'min_samples_leaf': 11, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:25,666] Trial 38 finished with value: 1.0 and parameters: {'n_estimators': 288, 'max_depth': 23, 'min_samples_split': 10, 'min_samples_leaf': 15, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:27,132] Trial 39 finished with value: 1.0 and parameters: {'n_estimators': 246, 'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:30,488] Trial 40 finished with value: 1.0 and parameters: {'n_estimators': 134, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:31,859] Trial 41 finished with value: 1.0 and parameters: {'n_estimators': 50, 'max_depth': 30, 'min_samples_split': 14, 'min_samples_leaf': 14, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:34,441] Trial 42 finished with value: 1.0 and parameters: {'n_estimators': 102, 'max_depth': 25, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:36,224] Trial 43 finished with value: 1.0 and parameters: {'n_estimators': 68, 'max_depth': 32, 'min_samples_split': 20, 'min_samples_leaf': 12, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:40,321] Trial 44 finished with value: 1.0 and parameters: {'n_estimators': 166, 'max_depth': 5, 'min_samples_split': 18, 'min_samples_leaf': 15, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:41,222] Trial 45 finished with value: 1.0 and parameters: {'n_estimators': 144, 'max_depth': 27, 'min_samples_split': 16, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:44,192] Trial 46 finished with value: 1.0 and parameters: {'n_estimators': 122, 'max_depth': 30, 'min_samples_split': 12, 'min_samples_leaf': 18, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:45,276] Trial 47 finished with value: 1.0 and parameters: {'n_estimators': 180, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 16, 'max_features': 'log2'}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:47,683] Trial 48 finished with value: 1.0 and parameters: {'n_estimators': 92, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 13, 'max_features': None}. Best is trial 0 with value: 1.0.
[I 2026-04-05 13:39:48,905] Trial 49 finished with value: 1.0 and parameters: {'n_estimators': 197, 'max_depth': 22, 'min_samples_split': 17, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 0 with value: 1.0.

In [25]:
best_model = RandomForestClassifier(**study.best_params)
best_model.fit(x_train, y_train)

RandomForestClassifier(max_depth=2, max_features=None, min_samples_leaf=5,
                       min_samples_split=16, n_estimators=81)

In [26]:
preds = best_model.predict(x_test)
accuracy = accuracy_score(y_test, preds)
f1 = f1_score(y_test, preds, average="weighted")

print(f"Accuracy: {accuracy} | F1-score: {f1}")

Accuracy: 1.0 | F1-score: 1.0

In [27]:
with open("intent_model.pkl", "wb") as f:
    pickle.dump(best_model, f)